fix: wf file

diff --git a/.github/workflows/docker-build-pr.yml b/.github/workflows/docker-build-pr.yml
--- a/.github/workflows/docker-build-pr.yml
+++ b/.github/workflows/docker-build-pr.yml
@@ -147,60 +147,59 @@ jobs:
           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f it/Dockerfile .
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
 
-    run-test:
-      name: Run integration tests
-      runs-on: ubuntu-latest
-      needs:
-        [build-storageapi, build-attestor, build-BI, build-wallet, build-it]
-      steps:
-        - name: Check out code
-          uses: actions/checkout@v3
-        - name: Configure AWS credentials
-          uses: aws-actions/configure-aws-credentials@v2
-          with:
-            aws-access-key-id: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
-            aws-secret-access-key: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
-            aws-region: us-east-1
-        - name: Login to Amazon ECR
-          id: login-ecr
-          uses: aws-actions/amazon-ecr-login@v1
-        - name: Set outputs
-          id: vars
-          run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
-        - name: Run test
-          env:
-            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-            ECR_REPOSITORY: dlc-integration-test
-            IMAGE_TAG: test-${{ steps.vars.outputs.sha_short }}
-          run: |
-            cd it && IMAGE_TAG=$IMAGE_TAG docker compose --profile it up -d
-        - name: Wait for the test container to complete
-          run: |
-            while true; do
-              status=$(docker ps -a -f name=integration-test --format '{{.Status}}')
-              exit_code=$(echo $status | awk '{print $2}' | tr -d '()')
+  run-test:
+    name: Run integration tests
+    runs-on: ubuntu-latest
+    needs: [build-storageapi, build-attestor, build-BI, build-wallet, build-it]
+    steps:
+      - name: Check out code
+        uses: actions/checkout@v3
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          aws-access-key-id: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
+          aws-region: us-east-1
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v1
+      - name: Set outputs
+        id: vars
+        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+      - name: Run test
+        env:
+          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          ECR_REPOSITORY: dlc-integration-test
+          IMAGE_TAG: test-${{ steps.vars.outputs.sha_short }}
+        run: |
+          cd it && IMAGE_TAG=$IMAGE_TAG docker compose --profile it up -d
+      - name: Wait for the test container to complete
+        run: |
+          while true; do
+            status=$(docker ps -a -f name=integration-test --format '{{.Status}}')
+            exit_code=$(echo $status | awk '{print $2}' | tr -d '()')
 
-              echo "Debug: status = $status"
-              echo "Debug: exit_code = $exit_code"
+            echo "Debug: status = $status"
+            echo "Debug: exit_code = $exit_code"
 
-              if [[ "$status" =~ "Exited" ]]; then
-                if [[ "$exit_code" == "0" ]]; then
-                  echo "Test succeeded"
-                  break
-                elif [[ "$exit_code" != "" ]]; then
-                  echo "Test failed with exit code $exit_code"
-                  docker logs integration-test
-                  exit 1
-                fi
-              else
-                echo "Waiting for test to complete, current status: $status"
+            if [[ "$status" =~ "Exited" ]]; then
+              if [[ "$exit_code" == "0" ]]; then
+                echo "Test succeeded"
+                break
+              elif [[ "$exit_code" != "" ]]; then
+                echo "Test failed with exit code $exit_code"
+                docker logs integration-test
+                exit 1
               fi
-              sleep 5
-            done
+            else
+              echo "Waiting for test to complete, current status: $status"
+            fi
+            sleep 5
+          done
 
-        - name: Retrieve test logs
-          run: |
-            docker logs integration-test
+      - name: Retrieve test logs
+        run: |
+          docker logs integration-test
 
-        - name: Remove containers
-          run: docker compose down
+      - name: Remove containers
+        run: docker compose down
